2024-11-05 21:29:39,852 - INFO - Running LED.py with model LongT5ForConditionalGeneration.from_pretrained('Stancld/longt5-tglobal-large-16384-pubmed-3k_steps')...
2024-11-05 21:29:49,114 - ERROR - An error occurred while running LED.py: Command '['python3', 'LED.py', 'config.yaml']' returned non-zero exit status 1.
2024-11-05 21:29:49,114 - INFO - Running generate_summary.py with initial configuration...
2024-11-05 21:29:53,967 - ERROR - An error occurred while running generate_summaries.py: Command '['python3', 'generate_summaries.py', 'config.yaml']' returned non-zero exit status 1.
2024-11-05 21:29:53,970 - INFO - Running LED.py with model AutoModelForSeq2SeqLM.from_pretrained('Stancld/long-t5-tglobal-base')...
2024-11-05 21:31:40,495 - INFO - Running LED.py with model LongT5ForConditionalGeneration.from_pretrained('Stancld/longt5-tglobal-large-16384-pubmed-3k_steps')...
2024-11-05 21:31:45,868 - ERROR - An error occurred while running LED.py: Command '['python3', 'LED.py', './config.yaml']' returned non-zero exit status 1.
2024-11-05 21:31:45,868 - INFO - Running generate_summary.py with initial configuration...
2024-11-05 21:33:16,468 - INFO - Running LED.py with model LongT5ForConditionalGeneration.from_pretrained('Stancld/longt5-tglobal-large-16384-pubmed-3k_steps')...
